import toga, os
import asyncio
import numpy as np
from toga.style import Pack
from toga.style.pack import LEFT, CENTER,ROW, COLUMN
from framesCounter import FramesCounter
from displayPlots import DisplayPlots

"""
This python module calculates the velocity autocorrelation function (VAF)
using the TRAJECTORY file generated by the CPMD program.
"""

class CorrelationFunction(FramesCounter, DisplayPlots):
    async def read_params(self, widget):
        """Read and validate the input parameters."""

        async def read_input(text_input, field_name, expected_type):
            value = text_input.value.strip()
            if not value:
                await self.main_window.error_dialog(
                    "Error", f"Please input a valid value for {field_name}."
                )
                return None
            try:
                return expected_type(value)
            except ValueError as e:
                await self.main_window.error_dialog(
                    "Error", f"Invalid format for {field_name}: {e}"
                )
                return None

        # Read and validate inputs
        self.start_frame = await read_input(
            self.textInput_start_frame, "start frame for the autocorrelation function", int
        )
        if self.start_frame is None:
            return

        self.stop_frame = await read_input(
            self.textInput_stop_frame, "stop frame for the autocorrelation function", int
        )
        if self.stop_frame is None:
            return

        self.num_frame_acf = await read_input(
            self.textInput_num_frames, "number of frames for each autocorrelation function", int
        )
        if self.num_frame_acf is None:
            return
        self.time_step = await read_input(
            self.textInput_time_step, "simulation time step", float
        )
        if self.time_step is None:
            return
        
        self.sampling_interval = await read_input(
            self.textInput_sampling_interval, "number of frames for each autocorrelation function", int
        )
        if self.sampling_interval is None:
            return

        update_text = (
            f"{'Starting frame for ACF':<30} {self.start_frame:>20}\n"
            f"{'Stop frame for ACF':<30}{self.stop_frame:>20}\n"
            f"{'Number of frames for each ACF':<30}{self.num_frame_acf:>20}\n"
            f"{'Simulation time step':<30}{self.time_step:>20}\n"
            f"{'Sampling interval':<30}{self.sampling_interval:>20}\n"
        )
        self.multi_line_text.value = update_text

    async def read_GEOMETRY_xyz(self, widget):
        """Read the GEOMETRY.xyz file and display its content."""

        self.symbols = []

        try:
            self.geom = await self.main_window.open_file_dialog("Open GEOMETRY.xyz file")
            if self.geom:
                self.textInput_geom.value = f"{self.geom}"
            else:
                await self.main_window.info_dialog("Warning", "No file was selected!")
                return

        except Exception as e:
            await self.main_window.error_dialog("Error", f"Failed to open file: {e}")
            return

        self.output_dir = os.path.dirname(self.geom)

        try:
            with open(self.geom, "r") as f:
                lines = f.readlines()
                if not lines:
                    await self.main_window.error_dialog(
                        "Error", "The GEOMETRY.xyz file is empty!"
                    )
                    return
                self.num_atoms = int(lines[0].strip())
                for line in lines[2:]:
                    tokens = line.strip().split()
                    if tokens:
                        self.symbols.append(tokens[0])

                self.multi_line_text.value = ''.join(lines)

        except Exception as e:
            await self.main_window.error_dialog(
                "Error", f"Failed to read file: {e}"
            )
            return

    async def read_TRAJECTORY(self, widget):
        try:
            self.trajectory = await self.main_window.open_file_dialog("Open TRAJECTORY file")
            if self.trajectory:
                self.textInput_trajectory.value = f"{self.trajectory}"
                await self.count_frames(widget)
            else:
                await self.main_window.info_dialog("Warning", "No file was selected!")
                return

        except Exception as e:
            await self.main_window.error_dialog(
                "Error", f"Failed to open file: {e}"
            )
            return

    async def count_frames(self, widget):
        """
        Count the total number of frames in the TRAJECTORY file and validate their integrity.
        """
        self.num_frames = 0
        num_lines = 0

        try:
            with open(self.trajectory, 'r') as f:
                while True:
                    frame = []
                    for _ in range(self.num_atoms):
                        line = f.readline()
                        if not line:
                            break
                        frame.append(line)
                        num_lines += 1
                    if len(frame) < self.num_atoms:
                        break  # End of file
                    self.num_frames += 1

                    if self.num_frames % 100 == 0:
                        self.progress_label.text = f"{self.num_frames}"
                        await asyncio.sleep(0)

                self.progress_label.text = f"Frames: {self.num_frames}"

        except Exception as e:
            await self.main_window.error_dialog(
                "Error", f"Error while reading line {num_lines}: {e}"
            )
            return

        self.progress_label.text = f"{self.num_frames}"

        # Write TRAJEC.xyz file from TRAJECTORY file if switch is on
        if self.switch_traj_xyz.value:
            await self.write_TRAJEC_xyz()

    async def write_TRAJEC_xyz(self):
        """Write the new TRAJEC.xyz file from the TRAJECTORY file."""
        au = 0.52917720859
        self.progress_bar.start()
        try:
            trajec_xyz_path = os.path.join(self.output_dir, "newTRAJEC.xyz")
            with open(trajec_xyz_path, "w") as file1:
                with open(self.trajectory, 'r') as file2:
                    for frame in range(self.num_frames):
                        file1.write(f"{self.num_atoms}\n")
                        file1.write(f"Frame {frame+1} generated by gqteaWinToga from TRAJECTORY file\n")
                        for k in range(self.num_atoms):
                            line = file2.readline().strip().split()
                            if len(line) >= 4:
                                coords = [float(line[i]) * au for i in range(1, 4)]
                                file1.write(f"{self.symbols[k]:<4s}{coords[0]:>14.7f}{coords[1]:>14.7f}{coords[2]:>14.7f}\n")
                            else:
                                await self.main_window.error_dialog(
                                    "Error", f"Invalid line format in TRAJECTORY file at frame {frame+1}"
                                )
                                return

                        if frame % 500 == 0:
                            update_progress_bar = (frame / self.num_frames) * 100
                            self.progress_bar.value = update_progress_bar

                        if frame == self.num_frames - 1:
                            self.progress_bar.value = 100
                            self.progress_bar.stop()
        except Exception as e:
            await self.main_window.error_dialog(
                "Error", f"Failed to write TRAJEC.xyz file: {e}"
            )
            return

    async def autocorrelation_function(self):
        """Calculate the Position Autocorrelation Function (PAF) and Velocity Autocorrelation Function (VAF)."""
        try:
            start_frame = self.start_frame
            stop_frame = self.stop_frame

            if stop_frame > self.num_frames:
                await self.main_window.dialog(toga.ErrorDialog(
                    "Error", "The stop frame must be less than the total number of frames")
                )
                return

            num_frames_per_step = self.num_frame_acf

        except ValueError as e:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", f"Invalid input format: {e}")
            )
            return

        try:
            with open(self.trajectory, 'r') as f:
                # Skip frames up to start_frame
                for _ in range((start_frame - 1) * self.num_atoms):
                    f.readline()

                step = start_frame
                num_acf = 0

                # Setting the length of paf and vaf to num_frames_per_step - 1 to 
                # ensure that each element corresponds to a valid time lag k for which data exists.
                paf = np.zeros(num_frames_per_step - 1)
                vaf = np.zeros(num_frames_per_step - 1)
                
                self.progress_bar.start()
                while step <= (stop_frame - num_frames_per_step):
                    coords_ref = []
                    coords = []

                    # Read reference frame
                    for _ in range(self.num_atoms):
                        line = f.readline().strip().split()
                        if len(line) >= 7:
                            coords_ref.append([float(x) for x in line[1:7]])
                        else:
                            await self.main_window.dialog(toga.ErrorDialog(
                                "Error", f"Invalid line format in TRAJECTORY file at frame {step}")
                            )
                            return

                    # range(num_frames_per_step - 1) ensures that index will always be
                    # less than len(coords), preventing out-of-bounds access.
                    for _ in range(num_frames_per_step - 1):
                        for _ in range(self.num_atoms):
                            line = f.readline().strip().split()
                            if len(line) >= 7:
                                coords.append([float(x) for x in line[1:7]])
                            else:
                                await self.main_window.dialog(toga.ErrorDialog(
                                    "Error", f"Invalid line format in TRAJECTORY file at frame {step}")
                                )
                                return

                    # Calculate PAF and VAF
                    for k in range(num_frames_per_step - 1):
                        paf_tmp = 0.0
                        vaf_tmp = 0.0
                        for n in range(self.num_atoms):
                            index = k * self.num_atoms + n
                            if index < len(coords):
                                paf_tmp += np.dot(coords_ref[n][0:3], coords[index][0:3])
                                vaf_tmp += np.dot(coords_ref[n][3:6], coords[index][3:6])
                        paf[k] += paf_tmp / self.num_atoms
                        vaf[k] += vaf_tmp / self.num_atoms

                    self.multi_line_text.value = f"{step} frames out of a total of {stop_frame}"
                    num_acf += 1
                    step += num_frames_per_step

                    update_progress_bar = (step / (stop_frame - start_frame)) * 100
                    self.progress_bar.value = update_progress_bar
                    
                self.progress_bar.value = 100
                self.progress_bar.stop()

                self.paf = paf / num_acf
                self.vaf = vaf / num_acf

                # Scale the autocorrelation function to be in [-1,1]
                self.paf /= np.max(np.abs(self.paf))
                self.vaf /= np.max(np.abs(self.vaf))

        except Exception as e:
            await self.main_window.error_dialog(
                "Error", f"An error occurred during the autocorrelation calculation: {e}"
            )
            return

        # Save and display results
        self.multi_line_text.value += f"\nNumber of ACF for average: {num_acf}\n"
        await self.save_and_display_results(self.paf, "PAF")
        await self.save_and_display_results(self.vaf, "VAF")

    async def save_and_display_results(self, data, label):
        """Save and display results for PAF or VAF."""
        try:
            output_file = os.path.join(self.output_dir, f"{label}.dat")
            with open(output_file, "w") as f:
                for i, value in enumerate(data, 1):
                    f.write(f"{i:<10d}{value:>7.5f}\n")
        except Exception as e:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", f"Error saving {label}: {e}\n")
            )
            return

        self.multi_line_text.value += f"\n{label}\n"

        for i, value in enumerate(data, 1):
            self.multi_line_text.value += f"{i:<10d}{value:>7.5f}\n"

    def ACFplot(self):
        # Plot for Position Autocorrelation Function (PAF)
        x_axis = range(len(self.paf))
        y_axis = self.paf

        plot_number = 1
        plot_xlabel = "Frames per PAF step"
        plot_ylabel = "PAF"
        plot_title = "Position Autocorrelation Function"

        # Save the plot to a file
        self.save_plots(plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title)

        # Plot for Velocity Autocorrelation Function (VAF)
        plot_number = 2
        x_axis = range(len(self.vaf))
        y_axis = self.vaf
        plot_xlabel = "Frames per VAF step"
        plot_ylabel = "VAF"
        plot_title = "Velocity Autocorrelation Function"

        # Save the plot to a file
        self.save_plots(plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title)


    async def calculate_psd(self):
        """
        Calculate the Power Spectral Density (PSD) using FFT from the VAF.dat file.

        Parameters:
        - vaf_file: str, path to the VAF.dat file.
        - output_psd_file: str, path to save the PSD data (CSV format).
        - output_plot_file: str, path to save the PSD plot (PNG format).
        - timestep: float, time interval between data points in the VAF.dat file.

        Outputs:
        - PSD data saved to `output_psd_file`.
        - PSD plot saved to `output_plot_file`.
        """
        vaf_file = f"{self.output_dir}/VAF.dat"
        output_psd_file = f"{self.output_dir}/PSD.dat"

        # Time interval in seconds between data points in the VAF.dat file
        timestep = 0.02418884326505 * self.time_step * self.sampling_interval * 1e-15

        try:
            # Load the second column of the VAF file
            vaf_values = np.loadtxt(vaf_file, usecols=1)

            # Perform FFT and calculate PSD
            fft_result = np.fft.fft(vaf_values)
            power_spectrum = np.abs(fft_result) ** 2

            # Calculate frequencies
            num_points = len(vaf_values)
            frequencies = np.fft.fftfreq(num_points, d=timestep)

            # Stack frequencies and power_spectrum for saving
            psd_data = np.column_stack((frequencies, power_spectrum))

            # Save the PSD data to a CSV file
            np.savetxt(
                output_psd_file,
                psd_data,
                delimiter=",",
                header="Frequency,Power",
                comments="",
                fmt="%.5f",
            )

            # Plot the PSD
            plot_number = 3
            x_axis = frequencies[: num_points // 2]
            y_axis = power_spectrum[: num_points // 2]  # Positive frequencies only
            plot_title = "Power Spectral Density (PSD) from VAF"
            plot_xlabel = "Frequency (Hz)"
            plot_ylabel = "Power"

            # Save the plot to a file
            self.save_plots(
                plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title
            )

        except Exception as e:
            await self.main_window.dialog(toga.ErrorDialog(f"An error occurred: {e}"))



    # async def calculate_psd(self):
    #     """
    #     Calculate the Power Spectral Density (PSD) using FFT from the VAF.dat file.
        
    #     Parameters:
    #     - vaf_file: str, path to the VAF.dat file.
    #     - output_psd_file: str, path to save the PSD data (CSV format).
    #     - output_plot_file: str, path to save the PSD plot (PNG format).
    #     - timestep: float, time interval between data points in the VAF.dat file.
        
    #     Outputs:
    #     - PSD data saved to `output_psd_file`.
    #     - PSD plot saved to `output_plot_file`.
    #     """
    #     vaf_file = f"{self.output_dir}/VAF.dat"
    #     output_psd_file = f"{self.output_dir}/PSD.dat"
        
    #     # Time interval in seconds between data points in the VAF.dat file
    #     timestep = 0.02418884326505*self.time_step*self.sampling_interval*1e-15  

    #     try:
    #         # Load the second column of the VAF file
    #         vaf_data = pd.read_csv(vaf_file, delim_whitespace=True, header=None)
    #         vaf_values = vaf_data[1].values  # Extract the second column

    #         # Perform FFT and calculate PSD
    #         fft_result = np.fft.fft(vaf_values)
    #         power_spectrum = np.abs(fft_result)**2

    #         # Calculate frequencies
    #         num_points = len(vaf_values)
    #         frequencies = np.fft.fftfreq(num_points, d=timestep)

    #         # Save the PSD data to a CSV file
    #         psd_data = pd.DataFrame({'Frequency': frequencies, 'Power': power_spectrum})
    #         psd_data.to_csv(output_psd_file, index=False, float_format="%.5f")

    #         # Plot the PSD
    #         plot_number = 3
    #         x_axis = frequencies[:num_points // 2]
    #         y_axis = power_spectrum[:num_points // 2]  # Positive frequencies only
    #         plot_title="Power Spectral Density (PSD) from VAF"
    #         plot_xlabel="Frequency (Hz)"
    #         plot_ylabel="Power"

    #         # Save the plot to a file
    #         self.save_plots(plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title)

    #     except Exception as e:
    #         await self.main_window.dialog(toga.ErrorDialog(f"An error occurred: {e}")
    #         )


class AutoCorrelationFunctionUI(CorrelationFunction):
    def __init__(self, *args):
        self.layout_main_window(*args)

    def layout_main_window(self, widget):
        # Create the main window
        self.main_window = toga.Window(
            title="Auto Correlation Function - ACF",
            size=(700, 600),
        )

        # Define common styles
        heading_style = Pack(
            font_size=18, font_weight="bold", text_align=LEFT, padding=(0, 0, 10, 0)
        )
        label_style = Pack(
            padding=(0, 0, 5, 5), text_align=LEFT, width=200
        )
        input_style = Pack(flex=1, padding=(5, 5))
        button_style = Pack(padding=5, width=100)
        box_style = Pack(direction=ROW, alignment=CENTER, padding=(0, 0, 5, 0))

        # Main container
        main_box = toga.Box(style=Pack(direction=COLUMN, padding=20))

        box_title = toga.Box(
            style=Pack(
                direction=ROW,
                alignment=CENTER,
                padding=(0, 0, 10, 0),
            )
        )

        sub_box_title = toga.Box(style=Pack(width=410))
        sub_box_empty = toga.Box(style=Pack(width=140))
        sub_box_progress = toga.Box(style=Pack(width=100))

        box_title.add(sub_box_title)
        box_title.add(sub_box_empty)
        box_title.add(sub_box_progress)

        # Title
        title_label = toga.Label("Autocorrelation Function - ACF", style=heading_style)
        empty_label = toga.Label(" ", style=heading_style)
        self.progress_label = toga.Label(" ", style=heading_style)

        sub_box_title.add(title_label)
        sub_box_empty.add(empty_label)
        sub_box_progress.add(self.progress_label)

        main_box.add(box_title)

        # Input fields with labels
        input_fields = [
            (
                "Starting frame for VAF and PAF:",
                "Enter starting frame for velocity and position correlation function",
                "textInput_start_frame",
            ),
            (
                "Stop frame for VAF and PAF:",
                "Enter stop frame for velocity and position correlation function",
                "textInput_stop_frame",
            ),
            (
                "Number of frames for each ACF:",
                "Enter the number of frames for each PAF and VAF",
                "textInput_num_frames",
            ),
            (
                "Simulation time step:",
                "Enter the simulation time step in atomic units",
                "textInput_time_step",
            ),
            (
                "Sampling interval:",
                "Enter the sampling interval between two collected frames",
                "textInput_sampling_interval",
            ),
        ]

        for label_text, placeholder, attr_name in input_fields:
            box = toga.Box(style=box_style)
            label = toga.Label(label_text, style=label_style)
            text_input = toga.TextInput(placeholder=placeholder, style=input_style)
            setattr(self, attr_name, text_input)
            box.add(label)
            box.add(text_input)
            main_box.add(box)

        # Switch to save augmented TRAJEC.xyz data
        self.switch_traj_xyz = toga.Switch(
            "Check box to create TRAJEC.xyz file from TRAJECTORY file",
            style=Pack(text_align=LEFT)
        )
        self.switch_psd = toga.Switch(
            "Check box for Power Spectral Density (PSD) calculation",
            style=Pack(text_align=LEFT)
        )

        # GEOMETRY.xyz file selection button
        geom_box = toga.Box(style=box_style)
        geom_label = toga.Label("Select GEOMETRY.xyz file:", style=label_style)
        self.textInput_geom = toga.TextInput(
            placeholder="Click Browse to select GEOMETRY.xyz file",
            style=input_style,
        )
        browse_geom_button = toga.Button(
            "Browse", on_press=self.read_GEOMETRY_xyz, style=button_style
        )
        geom_box.add(geom_label)
        geom_box.add(self.textInput_geom)
        geom_box.add(browse_geom_button)

        # TRAJECTORY file selection button
        traj_box = toga.Box(style=box_style)
        traj_label = toga.Label("Select TRAJECTORY file:", style=label_style)
        self.textInput_trajectory = toga.TextInput(
            placeholder="Click Browse to select TRAJECTORY file",
            style=input_style,
        )
        browse_traj_button = toga.Button(
            "Browse", on_press=self.read_TRAJECTORY, style=button_style
        )
        traj_box.add(traj_label)
        traj_box.add(self.textInput_trajectory)
        traj_box.add(browse_traj_button)

        # Progress bar
        self.progress_bar = toga.ProgressBar(max=100)
        main_box.add(geom_box)
        main_box.add(traj_box)
        main_box.add(self.switch_traj_xyz)
        main_box.add(self.switch_psd)
        main_box.add(self.progress_bar)

        # Multi-line text input for output
        self.multi_line_text = toga.MultilineTextInput(
            style=Pack(flex=1, padding=(5, 0), font_size=11)
        )
        self.multi_line_text.value = (
            "\n  AUTOCORRELATION FUNCTION FROM TRAJECTORY FILE FROM CPMD RUN"
        )
        main_box.add(self.multi_line_text)

        # Buttons at the bottom
        button_box = toga.Box(
            style=Pack(direction=ROW, alignment=CENTER, padding_top=5)
        )
        self.btn_input_params = toga.Button(
            "Read Params", style=button_style, on_press=self.read_params
        )
        self.btn_execute = toga.Button(
            "ACF calculation", style=button_style, on_press=self.workflow
        )
        self.btn_close = toga.Button(
            "Close", style=button_style, on_press=self.closeTopLevel
        )
        button_box.add(self.btn_input_params)
        button_box.add(self.btn_execute)
        button_box.add(self.btn_close)
        main_box.add(button_box)

        # Set the content of the main window
        self.main_window.content = main_box
        self.main_window.show()

    async def workflow(self, widget):
        await self.read_params(widget)  # Read and validate input parameters
        await self.autocorrelation_function()
        self.ACFplot()
        if self.switch_psd.value:
            await self.calculate_psd()
        self.display_plots()

    def closeTopLevel(self, widget):
        self.main_window.close()
