import toga, os
import asyncio
import numpy as np
import scipy.fft as sfft
from toga.style import Pack
from toga.style.pack import LEFT, CENTER,ROW, COLUMN
from framesCounter import FramesCounter
from displayPlots import DisplayPlots
from help import AtomicData

"""
This python module calculates the velocity autocorrelation function (VAF)
using the TRAJECTORY file generated by the CPMD program.
"""

class CorrelationFunction(FramesCounter, DisplayPlots):
    async def read_params(self, widget) -> bool:
        """Read and validate the input parameters. Returns True on success."""

        async def read_input(text_input, field_name, expected_type):
            value = text_input.value.strip()
            if not value:
                await self.main_window.dialog(
                    toga.ErrorDialog("Error", f"Please input a valid value for {field_name}.")
                )
                return None
            try:
                return expected_type(value)
            except ValueError as e:
                await self.main_window.dialog(
                    toga.ErrorDialog("Error", f"Invalid format for {field_name}: {e}")
                )
                return None

        # Read and validate inputs
        self.start_frame = await read_input(
            self.textInput_start_frame, "start frame for the autocorrelation function", int
        )
        if self.start_frame is None:
            return False

        self.stop_frame = await read_input(
            self.textInput_stop_frame, "stop frame for the autocorrelation function", int
        )
        if self.stop_frame is None:
            return False

        self.num_frame_acf = await read_input(
            self.textInput_num_frames, "number of frames for each autocorrelation function", int
        )
        if self.num_frame_acf is None:
            return False
        self.time_step = await read_input(
            self.textInput_time_step, "simulation time step", float
        )
        if self.time_step is None:
            return False

        self.sampling_interval = await read_input(
            self.textInput_sampling_interval, "sampling interval", int
        )
        if self.sampling_interval is None:
            return False

        # Cross-field validation
        if self.start_frame < 1:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", "The start frame must be a positive integer (>= 1).")
            )
            return False
        if self.stop_frame <= self.start_frame:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", "The stop frame must be greater than the start frame.")
            )
            return False
        if self.num_frame_acf < 2:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", "The number of frames for each ACF must be at least 2.")
            )
            return False
        if self.time_step <= 0 or self.sampling_interval <= 0:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", "Time step and sampling interval must be greater than zero.")
            )
            return False

        update_text = (
            f"{'Starting frame for ACF':<30} {self.start_frame:>20}\n"
            f"{'Stop frame for ACF':<30}{self.stop_frame:>20}\n"
            f"{'Number of frames for each ACF':<30}{self.num_frame_acf:>20}\n"
            f"{'Simulation time step':<30}{self.time_step:>20}\n"
            f"{'Sampling interval':<30}{self.sampling_interval:>20}\n"
        )
        self.multi_line_text.value = update_text
        return True

    async def read_GEOMETRY_xyz(self, widget):
        """Read the GEOMETRY.xyz file and display its content."""

        self.symbols = []

        try:
            self.geom = await self.main_window.dialog(
                toga.OpenFileDialog("Open GEOMETRY.xyz file")
            )
            if self.geom:
                self.textInput_geom.value = f"{self.geom}"
            else:
                await self.main_window.dialog(
                    toga.InfoDialog("Warning", "No file was selected!")
                )
                return

        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"Failed to open file: {e}")
            )
            return

        self.output_dir = os.path.dirname(self.geom)

        try:
            with open(self.geom, "r") as f:
                lines = f.readlines()
                if not lines:
                    await self.main_window.dialog(
                        toga.ErrorDialog("Error", "The GEOMETRY.xyz file is empty!")
                    )
                    return
                self.num_atoms = int(lines[0].strip())
                for line in lines[2:]:
                    tokens = line.strip().split()
                    if tokens:
                        self.symbols.append(tokens[0])

                self.multi_line_text.value = ''.join(lines)

        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"Failed to read file: {e}")
            )
            return

    async def read_TRAJECTORY(self, widget):
        try:
            self.trajectory = await self.main_window.dialog(
                toga.OpenFileDialog("Open TRAJECTORY file")
            )
            if self.trajectory:
                self.textInput_trajectory.value = f"{self.trajectory}"
                await self.count_frames(widget)
            else:
                await self.main_window.dialog(
                    toga.InfoDialog("Warning", "No file was selected!")
                )
                return

        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"Failed to open file: {e}")
            )
            return

    @staticmethod
    def _is_data_line(tokens) -> bool:
        """True if `tokens` looks like a TRAJECTORY atom line (step + 6 values).

        A real atom line has 7 columns; a CPMD restart marker
        (``<<<<<<  NEW DATA  >>>>>>``) splits into 4 tokens and a blank line into
        0, so a length test alone rejects the non-data lines. Float parsing is
        deliberately avoided here for speed (the actual numeric conversion happens
        once, when the values are stored).
        """
        return len(tokens) >= 7

    @staticmethod
    def _fft_autocorrelation(series3d, max_lag, col_weights=None):
        """Autocorrelation C(k) = <x(t).x(t+k)> via the Wiener-Khinchin theorem.

        `series3d` has shape (N, num_atoms, 3). The correlation is summed over the
        xyz components and atoms (optionally mass-weighted through `col_weights`)
        and averaged over all time origins, exactly reproducing the direct
        "mean over N-k origins" estimator (to ~1e-15) but in O(N log N) instead of
        O(N * max_lag). The result is normalized so that C[0] = 1.
        """
        N, A, D = series3d.shape
        series = series3d.reshape(N, A * D)
        nfft = sfft.next_fast_len(2 * N)
        # FFT along the time axis of every (atom, component) column at once.
        spectrum = sfft.rfft(series, n=nfft, axis=0, workers=-1)
        power = (spectrum.conj() * spectrum).real
        acf = sfft.irfft(power, n=nfft, axis=0, workers=-1)[:max_lag]  # (max_lag, A*D)
        if col_weights is None:
            R = acf.sum(axis=1)
        else:
            R = acf @ col_weights
        R = R / (N - np.arange(max_lag))   # divide by #origins == the original .mean()
        return R / R[0] if R[0] != 0 else R

    def _next_atom_tokens(self, f):
        """Next valid atom line as a token list, skipping non-data lines.

        CPMD appends a restart marker (``<<<<<<  NEW DATA  >>>>>>``) and may leave
        blank lines when a run is continued; these must be skipped so the atom
        framing stays aligned. Returns None at end of file.
        """
        while True:
            line = f.readline()
            if not line:
                return None
            tokens = line.split()
            if self._is_data_line(tokens):
                return tokens
            # Count skipped restart markers for user feedback.
            if line.strip():
                self._restart_markers = getattr(self, "_restart_markers", 0) + 1

    async def count_frames(self, widget):
        """
        Count the total number of complete frames in the TRAJECTORY file,
        skipping CPMD restart markers / blank lines so the framing stays aligned.
        """
        self.num_frames = 0
        self._restart_markers = 0

        # Lightweight status message instead of a continuously updated frame
        # counter (which marshalled a widget update to the UI thread every
        # hundred frames and slowed the loading down).
        self.progress_label.text = " "
        self.multi_line_text.value = "Loading TRAJECTORY file. Please wait..."
        await asyncio.sleep(0)   # let the message paint before the blocking count

        try:
            with open(self.trajectory, 'r') as f:
                while True:
                    complete = True
                    for _ in range(self.num_atoms):
                        if self._next_atom_tokens(f) is None:
                            complete = False
                            break
                    if not complete:
                        break  # End of file (partial trailing frame ignored)
                    self.num_frames += 1

                    # Yield occasionally (no per-frame widget updates) so the
                    # window stays responsive without slowing the count.
                    if self.num_frames % 5000 == 0:
                        await asyncio.sleep(0)

        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"Error while counting frames: {e}")
            )
            return

        message = f"TRAJECTORY loaded: {self.num_frames} frames."
        if self._restart_markers:
            message += (
                f"\n{self._restart_markers} CPMD restart marker(s) "
                f"(e.g. '<<<<<< NEW DATA >>>>>>') detected and skipped; "
                f"frames on either side are treated as one continuous trajectory."
            )
        self.multi_line_text.value = message

        # Populate control-panel defaults (whole trajectory) for any field the
        # user has left blank, so the tool is usable without manual entry.
        self._apply_frame_defaults()

        # Write TRAJEC.xyz file from TRAJECTORY file if switch is on
        if self.switch_traj_xyz.value:
            await self.write_TRAJEC_xyz()

    def _default_num_frame_acf(self) -> int:
        """Default correlation length (frames) for the VAF/PAF.

        Uses ~10% of the trajectory length, so that >= ~90% of the frames remain
        available as time origins for averaging (statistical reliability), with a
        floor of 2 and a cap of 2000 frames to bound the computational cost and
        keep the power-spectrum frequency resolution sensible on very long
        trajectories.
        """
        return max(2, min(self.num_frames // 10, 2000))

    def _apply_frame_defaults(self) -> None:
        """Fill any empty frame/ACF field with whole-trajectory defaults."""
        if not getattr(self, "num_frames", 0):
            return
        if not self.textInput_start_frame.value.strip():
            self.textInput_start_frame.value = "1"
        if not self.textInput_stop_frame.value.strip():
            self.textInput_stop_frame.value = str(self.num_frames)
        if not self.textInput_num_frames.value.strip():
            self.textInput_num_frames.value = str(self._default_num_frame_acf())

    async def write_TRAJEC_xyz(self):
        """Write the new TRAJEC.xyz file from the TRAJECTORY file."""
        au = 0.52917720859
        self.multi_line_text.value = "Writing newTRAJEC.xyz file. Please wait..."
        await asyncio.sleep(0)   # paint the message before the blocking write
        try:
            trajec_xyz_path = os.path.join(self.output_dir, "newTRAJEC.xyz")
            with open(trajec_xyz_path, "w") as file1:
                with open(self.trajectory, 'r') as file2:
                    for frame in range(self.num_frames):
                        file1.write(f"{self.num_atoms}\n")
                        file1.write(f"Frame {frame+1} generated by gqteaWinToga from TRAJECTORY file\n")
                        for k in range(self.num_atoms):
                            tokens = self._next_atom_tokens(file2)
                            if tokens is None:
                                await self.main_window.dialog(
                                    toga.ErrorDialog(
                                        "Error",
                                        f"Unexpected end of TRAJECTORY file at frame {frame+1}",
                                    )
                                )
                                return
                            coords = [float(tokens[i]) * au for i in range(1, 4)]
                            file1.write(f"{self.symbols[k]:<4s}{coords[0]:>14.7f}{coords[1]:>14.7f}{coords[2]:>14.7f}\n")

                        # Yield occasionally (no widget updates) to stay responsive.
                        if frame % 2000 == 0:
                            await asyncio.sleep(0)
        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"Failed to write TRAJEC.xyz file: {e}")
            )
            return

        self.multi_line_text.value = f"newTRAJEC.xyz written ({self.num_frames} frames)."

    async def autocorrelation_function(self) -> bool:
        """Calculate the Position (PAF) and Velocity (VAF) Autocorrelation Functions.

        Frames from start_frame to stop_frame are loaded once, then the
        autocorrelation is averaged over all available time origins (overlapping
        windows) up to a maximum lag of num_frame_acf frames. Lag 0 is included
        and each function is normalized by its value at lag 0, i.e. C(tau)/C(0).
        Positions are mean-subtracted per atom so the PAF reflects fluctuations
        about the average position rather than the absolute coordinates.

        Returns True on success, False if the calculation could not complete.
        """
        if not getattr(self, "trajectory", None):
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", "Load a TRAJECTORY file before running the calculation.")
            )
            return False
        if not getattr(self, "num_atoms", None):
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", "Load a GEOMETRY.xyz file so the number of atoms is known.")
            )
            return False

        start_frame = self.start_frame
        stop_frame = self.stop_frame
        max_lag = self.num_frame_acf

        if stop_frame > getattr(self, "num_frames", 0):
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", "The stop frame must be less than the total number of frames.")
            )
            return False

        n_read = stop_frame - start_frame + 1
        if max_lag > n_read:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error",
                f"Number of frames per ACF ({max_lag}) cannot exceed the number of "
                f"selected frames ({n_read}).")
            )
            return False

        # --- Load the requested frame range into one array (n_read, num_atoms, 6) ---
        # No progress bar / per-frame counter here: a single status message keeps
        # the UI responsive without the overhead of updating widgets in the loop.
        self.multi_line_text.value = "Loading TRAJECTORY file. Please wait..."
        await asyncio.sleep(0)   # paint the message before the blocking read
        try:
            data = np.empty((n_read, self.num_atoms, 6), dtype=float)
            with open(self.trajectory, 'r') as f:
                # Skip data lines before start_frame (restart markers skipped too).
                for _ in range((start_frame - 1) * self.num_atoms):
                    if self._next_atom_tokens(f) is None:
                        break

                for fi in range(n_read):
                    for a in range(self.num_atoms):
                        tokens = self._next_atom_tokens(f)
                        if tokens is None:
                            await self.main_window.dialog(toga.ErrorDialog(
                                "Error",
                                f"Unexpected end of TRAJECTORY file at frame "
                                f"{start_frame + fi}.")
                            )
                            return False
                        data[fi, a] = [float(x) for x in tokens[1:7]]

                    # Yield occasionally (no widget updates) to stay responsive.
                    if fi % 4000 == 0:
                        await asyncio.sleep(0)
        except Exception as e:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", f"An error occurred while reading the trajectory: {e}")
            )
            return False

        positions = data[:, :, 0:3].copy()
        velocities = data[:, :, 3:6]

        # Mean-subtract positions per atom so the PAF measures fluctuations
        # about the average position rather than the absolute coordinates.
        positions -= positions.mean(axis=0, keepdims=True)

        # A mass-weighted VAF is only needed when a mass-weighted power spectrum
        # (true vibrational DOS) is requested; skip the extra work otherwise.
        masses = self._atom_masses() if self._wants_mass_weighted_psd() else None

        # --- Correlate over all time origins via FFT (Wiener-Khinchin) ---
        # O(N log N) instead of O(N * max_lag); each call is normalized to C[0]=1.
        # Run sequentially so only one transform's memory is live at a time.
        self.multi_line_text.value = "Computing autocorrelation functions. Please wait..."
        await asyncio.sleep(0)   # paint the message before the (fast) FFT work
        try:
            paf = self._fft_autocorrelation(positions, max_lag)
            vaf = self._fft_autocorrelation(velocities, max_lag)

            vaf_mw = None
            if masses is not None:
                # Weight each (atom, xyz) column by that atom's mass.
                vaf_mw = self._fft_autocorrelation(
                    velocities, max_lag, col_weights=np.repeat(masses, 3)
                )
        except Exception as e:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", f"An error occurred during the autocorrelation calculation: {e}")
            )
            return False

        self.paf = paf
        self.vaf = vaf
        self.vaf_mw = vaf_mw   # None unless a mass-weighted PSD was requested

        # Partial VACFs for the requested element/atom-selection groups (only
        # needed when a partial power spectrum is requested). Computed here while
        # the per-atom velocities are still in memory.
        self.partial_vacfs = {}
        psd_on = getattr(self, "switch_psd", None) is not None and self.switch_psd.value
        if psd_on:
            for glabel, idx in self._parse_partial_groups():
                col_w = np.repeat(masses[idx], 3) if masses is not None else None
                self.partial_vacfs[glabel] = self._fft_autocorrelation(
                    velocities[:, idx, :], max_lag, col_weights=col_w
                )

        n_origins = n_read - max_lag + 1
        self.multi_line_text.value = (
            f"Frames analyzed: {n_read} (frames {start_frame}-{stop_frame})\n"
            f"Maximum lag: {max_lag} frames\n"
            f"Time origins averaged per lag: up to {n_origins}\n"
        )
        await self.save_and_display_results(self.paf, "PAF")
        await self.save_and_display_results(self.vaf, "VAF")
        return True

    async def save_and_display_results(self, data, label):
        """Write the PAF/VAF data to <label>.dat (the full table is not echoed to
        the text field, which only shows the run summary)."""
        try:
            output_file = os.path.join(self.output_dir, f"{label}.dat")
            with open(output_file, "w") as f:
                for lag, value in enumerate(data):
                    f.write(f"{lag:<10d}{value:>7.5f}\n")
        except Exception as e:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", f"Error saving {label}: {e}\n")
            )
            return

    def ACFplot(self):
        # Plot for Position Autocorrelation Function (PAF)
        x_axis = range(len(self.paf))
        y_axis = self.paf

        plot_number = 1
        plot_xlabel = "Lag (frames)"
        plot_ylabel = "PAF"
        plot_title = "Position Autocorrelation Function"

        # Hand the curve to the interactive viewer; save_png=False so no static
        # PNG image files are left next to the trajectory.
        self.save_plots(plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title, save_png=False)

        # Plot for Velocity Autocorrelation Function (VAF)
        plot_number = 2
        x_axis = range(len(self.vaf))
        y_axis = self.vaf
        plot_xlabel = "Lag (frames)"
        plot_ylabel = "VAF"
        plot_title = "Velocity Autocorrelation Function"

        # Hand the curve to the interactive viewer; save_png=False so no static
        # PNG image files are left next to the trajectory.
        self.save_plots(plot_number, x_axis, y_axis, plot_xlabel, plot_ylabel, plot_title, save_png=False)


    # ------------------------------------------------------------------ #
    #  Power spectrum (vibrational density of states) helpers             #
    # ------------------------------------------------------------------ #
    # Frequency-unit conversion factors from Hz.
    _HZ_TO_CM1 = 1.0 / 2.99792458e10   # c in cm/s  ->  wavenumber (cm^-1)
    _HZ_TO_THZ = 1.0e-12

    def _wants_mass_weighted_psd(self) -> bool:
        """True if the user asked for a mass-weighted (true VDOS) spectrum."""
        sw = getattr(self, "switch_mass_weight", None)
        return bool(sw is not None and sw.value)

    def _atom_masses(self):
        """Per-atom mass array (num_atoms,) from the loaded symbols, or None."""
        symbols = getattr(self, "symbols", None)
        if not symbols or len(symbols) != getattr(self, "num_atoms", -1):
            return None
        return np.array(
            [AtomicData.atomic_masses.get(s, 1.0) for s in symbols], dtype=float
        )

    def _psd_window_choice(self) -> str:
        sel = getattr(self, "selection_window", None)
        return str(sel.value) if sel is not None else "Welch"

    def _psd_zero_pad_factor(self) -> int:
        field = getattr(self, "textInput_zero_pad", None)
        if field is None or not field.value.strip():
            return 5
        try:
            return max(0, int(field.value))
        except ValueError:
            return 5

    def _psd_freq_unit(self) -> str:
        sel = getattr(self, "selection_freq_unit", None)
        return str(sel.value) if sel is not None else "cm^-1"

    @staticmethod
    def _make_window(choice: str, n: int):
        """Return a length-n window array for the chosen type."""
        if choice == "Welch":
            k = np.arange(n)
            half = (n - 1) / 2.0
            return 1.0 - ((k - half) / half) ** 2
        if choice == "Hann":
            return np.hanning(n)
        return np.ones(n)   # "None" / rectangular

    def _spectrum_from_vacf(self, c, nfft, window_choice):
        """One-sided power spectrum |FFT|^2 of a VACF with the standard
        preprocessing: mean removal, mirror about t=0, window, zero-pad to nfft."""
        c = np.asarray(c, dtype=float)
        c = c - c.mean()
        c_sym = np.concatenate((c[::-1], c[1:]))
        c_win = c_sym * self._make_window(window_choice, c_sym.size)
        return np.abs(np.fft.rfft(c_win, n=nfft)) ** 2

    @staticmethod
    def _sanitize_label(label: str) -> str:
        """Filesystem-safe tag from a selection label (e.g. '1-8,H' -> '1_8_H')."""
        return "".join(ch if ch.isalnum() else "_" for ch in label).strip("_") or "sel"

    def _parse_partial_groups(self):
        """Parse the partial-VDOS selection field into [(label, atom_index_array)].

        The field holds ';'-separated groups; each group is a comma/space list of
        element symbols (e.g. 'H', 'O') and/or 1-based atom indices or ranges
        (e.g. '5', '1-8'). Element tokens expand to every atom of that element;
        indices are converted to 0-based. Unrecognized tokens and empty groups are
        skipped. Returns [] when the field is blank or nothing valid is given.
        """
        field = getattr(self, "textInput_partial", None)
        if field is None or not field.value.strip():
            return []
        symbols = getattr(self, "symbols", []) or []
        n = getattr(self, "num_atoms", 0)
        groups = []
        for raw_group in field.value.split(";"):
            raw_group = raw_group.strip()
            if not raw_group:
                continue
            idx = set()
            for tok in raw_group.replace(",", " ").split():
                if tok.isalpha():                                   # element symbol
                    element = tok.capitalize() if len(tok) > 1 else tok.upper()
                    idx.update(i for i, s in enumerate(symbols) if s == element)
                elif "-" in tok and all(p.isdigit() for p in tok.split("-", 1)):
                    lo, hi = (int(p) for p in tok.split("-", 1))    # index range
                    idx.update(i - 1 for i in range(lo, hi + 1) if 1 <= i <= n)
                elif tok.isdigit():                                 # single index
                    i = int(tok)
                    if 1 <= i <= n:
                        idx.add(i - 1)
            if idx:
                groups.append((raw_group, np.array(sorted(idx), dtype=int)))
        return groups

    async def calculate_psd(self):
        """Power spectrum / vibrational density of states from the VAF.

        Pipeline (Wiener-Khinchin route): take the velocity autocorrelation
        function C(t); remove its mean (kill the DC component); mirror it about
        t = 0 to a symmetric two-sided function (doubles the frequency
        resolution); apply a Welch/Hann window to suppress spectral leakage;
        zero-pad to interpolate the spectrum; FFT and take |.|^2. The one-sided
        spectrum is written and plotted against a physical frequency axis in the
        requested unit (cm^-1, THz or Hz). If the mass-weighting option is on,
        the mass-weighted VAF is used, giving the vibrational density of states.
        """
        mass_weighted = self._wants_mass_weighted_psd()
        vacf = self.vaf_mw if (mass_weighted and getattr(self, "vaf_mw", None) is not None) else getattr(self, "vaf", None)
        if mass_weighted and getattr(self, "vaf_mw", None) is None:
            mass_weighted = False   # masses unavailable; fall back to plain PSD
        if vacf is None:
            await self.main_window.dialog(toga.ErrorDialog(
                "Error", "Run the VAF calculation before computing the power spectrum.")
            )
            return

        try:
            c = np.asarray(vacf, dtype=float)
            if c.size < 2:
                await self.main_window.dialog(toga.ErrorDialog(
                    "Error", "The VAF is too short to compute a power spectrum.")
                )
                return

            # Shared FFT length and frequency axis (total and all partials use
            # the same window, zero-padding and frequency grid so they overlay).
            window_choice = self._psd_window_choice()
            npad = self._psd_zero_pad_factor()
            n_sym = 2 * c.size - 1
            nfft = 1
            while nfft < int((npad + 1) * n_sym):
                nfft *= 2

            dt = 0.02418884326505 * self.time_step * self.sampling_interval * 1e-15  # s
            freqs_hz = np.fft.rfftfreq(nfft, d=dt)
            unit = self._psd_freq_unit()
            if unit == "cm^-1":
                frequencies = freqs_hz * self._HZ_TO_CM1
            elif unit == "THz":
                frequencies = freqs_hz * self._HZ_TO_THZ
            else:
                unit = "Hz"
                frequencies = freqs_hz

            def normalized_spectrum(vac):
                p = self._spectrum_from_vacf(vac, nfft, window_choice)
                m = p.max()
                return p / m if m > 0 else p

            label = "VDOS" if mass_weighted else "PSD"

            def write_dat(name, power):
                path = os.path.join(self.output_dir, name)
                np.savetxt(
                    path, np.column_stack((frequencies, power)),
                    delimiter=",", header=f"Frequency({unit}),Power",
                    comments="", fmt="%.6e",
                )
                return path

            # Total spectrum (all atoms).
            total_power = normalized_spectrum(c)
            saved = [write_dat(f"{label}.dat", total_power)]
            series = [(frequencies, total_power, "Total")]

            # Partial spectra per element/atom-selection group, each normalized to
            # its own maximum so the peak positions of every group are visible.
            for glabel, gvacf in (getattr(self, "partial_vacfs", {}) or {}).items():
                p_power = normalized_spectrum(gvacf)
                saved.append(write_dat(f"{label}_{self._sanitize_label(glabel)}.dat", p_power))
                series.append((frequencies, p_power, glabel))

            title = "Vibrational DOS from VAF" if mass_weighted else "Power Spectrum from VAF"
            if len(series) > 1:
                self.save_multiseries_plot(
                    3, series, f"Frequency ({unit})", "Power (norm.)",
                    title + " (total + partials)",
                    save_png=False,
                )
            else:
                self.save_plots(
                    3, frequencies, total_power, f"Frequency ({unit})", "Power (norm.)", title,
                    save_png=False,
                )

            msg = (
                f"{label}: window={window_choice}, zero-pad x{npad}, unit={unit}\n"
                f"Saved: " + ", ".join(os.path.basename(s) for s in saved) + "\n"
            )
            if len(series) > 1:
                msg += "Partial curves are each normalized to their own maximum.\n"
            self.multi_line_text.value += msg

        except Exception as e:
            await self.main_window.dialog(
                toga.ErrorDialog("Error", f"An error occurred during the PSD calculation: {e}")
            )


class AutoCorrelationFunctionUI(CorrelationFunction):
    def __init__(self, *args):
        self.layout_main_window(*args)

    def layout_main_window(self, widget):
        # Create the main window
        self.main_window = toga.Window(
            title="Auto Correlation Function - ACF",
            size=(700, 600),
        )

        # Define common styles
        heading_style = Pack(
            font_size=18, font_weight="bold", text_align=LEFT, margin=(0, 0, 10, 0)
        )
        label_style = Pack(
            margin=(0, 0, 5, 5), text_align=LEFT, width=200
        )
        input_style = Pack(flex=1, margin=(5, 5))
        button_style = Pack(margin=5, width=100)
        box_style = Pack(direction=ROW, align_items=CENTER, margin=(0, 0, 5, 0))

        # Main container
        main_box = toga.Box(style=Pack(direction=COLUMN, margin=20))

        box_title = toga.Box(
            style=Pack(
                direction=ROW,
                align_items=CENTER,
                margin=(0, 0, 10, 0),
            )
        )

        sub_box_title = toga.Box(style=Pack(width=410))
        sub_box_empty = toga.Box(style=Pack(width=140))
        sub_box_progress = toga.Box(style=Pack(width=100))

        box_title.add(sub_box_title)
        box_title.add(sub_box_empty)
        box_title.add(sub_box_progress)

        # Title
        title_label = toga.Label("Autocorrelation Function - ACF", style=heading_style)
        empty_label = toga.Label(" ", style=heading_style)
        self.progress_label = toga.Label(" ", style=heading_style)

        sub_box_title.add(title_label)
        sub_box_empty.add(empty_label)
        sub_box_progress.add(self.progress_label)

        main_box.add(box_title)

        # Input fields with labels
        input_fields = [
            (
                "Starting frame for VAF and PAF:",
                "Leave blank to start at frame 1 (auto-filled when TRAJECTORY loads)",
                "textInput_start_frame",
            ),
            (
                "Stop frame for VAF and PAF:",
                "Leave blank to use the last frame (auto-filled when TRAJECTORY loads)",
                "textInput_stop_frame",
            ),
            (
                "Number of frames for each ACF:",
                "Leave blank for ~10% of the trajectory (auto-filled when TRAJECTORY loads)",
                "textInput_num_frames",
            ),
            (
                "Simulation time step:",
                "Enter the simulation time step in atomic units",
                "textInput_time_step",
            ),
            (
                "Sampling interval:",
                "Enter the sampling interval between two collected frames",
                "textInput_sampling_interval",
            ),
        ]

        for label_text, placeholder, attr_name in input_fields:
            box = toga.Box(style=box_style)
            label = toga.Label(label_text, style=label_style)
            text_input = toga.TextInput(placeholder=placeholder, style=input_style)
            setattr(self, attr_name, text_input)
            box.add(label)
            box.add(text_input)
            main_box.add(box)

        # Switch to save augmented TRAJEC.xyz data
        self.switch_traj_xyz = toga.Switch(
            "Check box to create TRAJEC.xyz file from TRAJECTORY file",
            style=Pack(text_align=LEFT)
        )
        self.switch_psd = toga.Switch(
            "Check box for Power Spectral Density (PSD) calculation",
            style=Pack(text_align=LEFT)
        )
        self.switch_mass_weight = toga.Switch(
            "Mass-weight the spectrum (true vibrational density of states)",
            style=Pack(text_align=LEFT)
        )

        # Power-spectrum options: window, zero-padding factor and frequency unit.
        psd_options_box = toga.Box(style=box_style)
        self.selection_window = toga.Selection(
            items=["Welch", "Hann", "None"], style=Pack(margin=(0, 5), width=110)
        )
        self.textInput_zero_pad = toga.TextInput(
            value="5", style=Pack(margin=(0, 5), width=60)
        )
        self.selection_freq_unit = toga.Selection(
            items=["cm^-1", "THz", "Hz"], style=Pack(margin=(0, 5), width=90)
        )
        psd_options_box.add(toga.Label("PSD window:", style=Pack(margin=(0, 5))))
        psd_options_box.add(self.selection_window)
        psd_options_box.add(toga.Label("Zero-pad x:", style=Pack(margin=(0, 5))))
        psd_options_box.add(self.textInput_zero_pad)
        psd_options_box.add(toga.Label("Frequency unit:", style=Pack(margin=(0, 5))))
        psd_options_box.add(self.selection_freq_unit)

        # Partial VDOS selection: overlay per-element / per-atom-group spectra on
        # the total to help assign vibrational modes.
        partial_box = toga.Box(style=box_style)
        self.textInput_partial = toga.TextInput(
            placeholder="Partial VDOS (optional): e.g. 'H,O' or '1-8,15'; separate groups with ';'",
            style=input_style,
        )
        partial_box.add(toga.Label("Partial VDOS groups:", style=label_style))
        partial_box.add(self.textInput_partial)

        # GEOMETRY.xyz file selection button
        geom_box = toga.Box(style=box_style)
        geom_label = toga.Label("Select GEOMETRY.xyz file:", style=label_style)
        self.textInput_geom = toga.TextInput(
            placeholder="Click Browse to select GEOMETRY.xyz file",
            style=input_style,
        )
        browse_geom_button = toga.Button(
            "Browse", on_press=self.read_GEOMETRY_xyz, style=button_style
        )
        geom_box.add(geom_label)
        geom_box.add(self.textInput_geom)
        geom_box.add(browse_geom_button)

        # TRAJECTORY file selection button
        traj_box = toga.Box(style=box_style)
        traj_label = toga.Label("Select TRAJECTORY file:", style=label_style)
        self.textInput_trajectory = toga.TextInput(
            placeholder="Click Browse to select TRAJECTORY file",
            style=input_style,
        )
        browse_traj_button = toga.Button(
            "Browse", on_press=self.read_TRAJECTORY, style=button_style
        )
        traj_box.add(traj_label)
        traj_box.add(self.textInput_trajectory)
        traj_box.add(browse_traj_button)

        main_box.add(geom_box)
        main_box.add(traj_box)
        main_box.add(self.switch_traj_xyz)
        main_box.add(self.switch_psd)
        main_box.add(self.switch_mass_weight)
        main_box.add(psd_options_box)
        main_box.add(partial_box)

        # Multi-line text input for output
        self.multi_line_text = toga.MultilineTextInput(
            style=Pack(flex=1, margin=(5, 0), font_size=11)
        )
        self.multi_line_text.value = (
            "\n  AUTOCORRELATION FUNCTION FROM TRAJECTORY FILE FROM CPMD RUN"
        )
        main_box.add(self.multi_line_text)

        # Buttons at the bottom
        button_box = toga.Box(
            style=Pack(direction=ROW, align_items=CENTER, margin_top=5)
        )
        self.btn_input_params = toga.Button(
            "Read Params", style=button_style, on_press=self.read_params
        )
        self.btn_execute = toga.Button(
            "ACF calculation", style=button_style, on_press=self.workflow
        )
        self.btn_close = toga.Button(
            "Close", style=button_style, on_press=self.closeTopLevel
        )
        button_box.add(self.btn_input_params)
        button_box.add(self.btn_execute)
        button_box.add(self.btn_close)
        main_box.add(button_box)

        # Set the content of the main window
        self.main_window.content = main_box
        self.main_window.show()

    async def workflow(self, widget):
        # Read and validate input parameters; bail out if anything is invalid.
        if not await self.read_params(widget):
            return
        if not await self.autocorrelation_function():
            return
        self.ACFplot()
        if self.switch_psd.value:
            await self.calculate_psd()
        self.display_plots()

    def closeTopLevel(self, widget):
        self.main_window.close()
